//
//  CollectionAnalysisView.swift
//  VisualIntelligencePipeline
//
//  Full CLaRa analysis modal — shows a detailed report of a session/collection's
//  contents with share and copy capabilities.
//

import SwiftUI
import DiverKit

struct CollectionAnalysisView: View {
    let sessionTitle: String
    @Binding var analysisText: String
    @Binding var isGenerating: Bool
    
    @Environment(\.dismiss) private var dismiss
    @State private var copied = false
    
    var body: some View {
        NavigationStack {
            ZStack {
                Color(.systemGroupedBackground).ignoresSafeArea()
                
                if isGenerating {
                    generatingView
                } else if analysisText.isEmpty {
                    emptyView
                } else {
                    analysisContent
                }
            }
            .navigationTitle("Full Analysis")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    Button("Done") { dismiss() }
                }
                
                ToolbarItemGroup(placement: .topBarTrailing) {
                    if !analysisText.isEmpty && !isGenerating {
                        ShareLink(item: shareableText) {
                            Image(systemName: "square.and.arrow.up")
                        }
                        
                        Button {
                            UIPasteboard.general.string = analysisText
                            withAnimation { copied = true }
                            DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
                                withAnimation { copied = false }
                            }
                        } label: {
                            Image(systemName: copied ? "checkmark" : "doc.on.doc")
                        }
                    }
                }
            }
        }
    }
    
    private var shareableText: String {
        """
        📊 Full Analysis: \(sessionTitle)
        Generated by Visual Intelligence (CLaRa 7B)
        
        \(analysisText)
        """
    }
    
    @ViewBuilder
    private var generatingView: some View {
        VStack(spacing: 20) {
            ProgressView()
                .scaleEffect(1.5)
            
            Text("Analyzing with CLaRa 7B...")
                .font(.headline)
                .foregroundStyle(.secondary)
            
            Text("Generating a detailed report of all items, metadata, and insights in this collection.")
                .font(.caption)
                .foregroundStyle(.tertiary)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 40)
        }
    }
    
    @ViewBuilder
    private var emptyView: some View {
        ContentUnavailableView(
            "No Analysis Available",
            systemImage: "sparkles",
            description: Text("CLaRa edge node may not be reachable. Try again when your Mac is nearby.")
        )
    }
    
    @ViewBuilder
    private var analysisContent: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                // Header
                HStack(spacing: 12) {
                    Image(systemName: "sparkles")
                        .font(.title2)
                        .foregroundStyle(.purple)
                    
                    VStack(alignment: .leading, spacing: 2) {
                        Text(sessionTitle)
                            .font(.headline)
                        Text("Generated by CLaRa 7B")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
                .padding(.bottom, 4)
                
                Divider()
                
                // Analysis text
                Text(analysisText)
                    .font(.body)
                    .lineSpacing(4)
                    .textSelection(.enabled)
            }
            .padding(20)
        }
    }
}
